[auth] # Authentication parameters can be overridden in .env file
username = "your_username"
password = "your_password"
group_id = "your_group_id"

[general]
seconds_to_sleep = 600

[logging]
level = "DEBUG"

[rules]
[rules.quarantine_after_event]
type = "QuarantineAfterEvent"
header_regex = ".*Americano.*"
quarantine_hours = 24
message = "Hi {firstName},\nYou were removed from the event \"{heading}\" because you played last time.\nPlease wait for at least 24 hours after the event ended before signing up."
enforced = true

[rules.max_per_week]
type = "MaxEventsPerWeek"
header_regex = ".*Americano.*"
max_events = 2
grace_hours = 24
message = "Hi {firstName},\nYou were removed from the event \"{heading}\" because you are only allowed to have two active sign-ups.\nEvents that start within the next 24 hours are not counted towards the total."
enforced = true
